dataset: mot

train_split: mot17_train_coco  # mot17_train_coco_dev_one_percent  #
val_split: mot17_train_cross_val_frame_0_5_to_1_0_coco  # mot17_train_cross_val_frame_0_5_to_0_51_coco__dev  #

mot_path_train: D:\data\__research_only\mot17 #  data/MOT17
mot_path_val: D:\data\__research_only\mot17 # data/MOT17

resume: '' # models/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint_hidden_dim_288.pth

epochs: 50
lr_drop: 10
